//
//  SwiftPlaygroundPattern.swift
//  Industrial Builder
//
//  Created by Artem on 27.03.2026.
//

import Foundation

public func swift_playground_pattern(
    name: String,
    modules_func: @escaping (URL) -> Void
) -> FilePattern
{
    .init(
        name: "\(name).swiftpm",
        children: [
            ContentView_file_pattern,
            MyApp_file_pattern,
            Package_file_pattern(name: name),
            .init(writing_func: modules_func)
        ]
    )
}

private var ContentView_file_pattern: FilePattern = .init(
    name: "ContentView.swift",
    data:
"""
import SwiftUI
import RealityKit

import IndustrialKit
import IndustrialKitUI

struct ContentView: View
{
    var body: some View
    {
        VStack(spacing: 16)
        {
            Image(systemName: "gear")
                .imageScale(.large)
                .foregroundColor(.accentColor)
            Text("Industrial App")
        }
    }
}
"""
)

private var MyApp_file_pattern: FilePattern = .init(
    name: "MyApp.swift",
    data:
"""
import SwiftUI

@main
struct MyApp: App
{
    var body: some Scene
    {
        WindowGroup
        {
            ContentView()
        }
    }
}
"""
)

private func Package_file_pattern(name: String) -> FilePattern
{
    .init(
        name: "Package.swift",
        data:
"""
// swift-tools-version: 6.2

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "\(name)",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "\(name)",
            targets: ["AppModule"],
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/MalkarovPark/IndustrialKit", "5.1.0"..<"6.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "IndustrialKit", package: "industrialkit"),
                .product(name: "IndustrialKitUI", package: "industrialkit")
            ],
            path: "."
        )
    ]
)
"""
    )
}
